apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql-deployment

spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mysql-db
  
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-container
          image: mysql
          ports:
            - containerPort: 3306
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
      #     volumeMounts:
      #       - name: mysql-persistent-storage # Define the volume mount
      #         mountPath: /var/lib/mysql
      # volumes:
      #   - name: mysql-persistent-storage # Define the volume
      #     persistentVolumeClaim:
      #       claimName: mysql-pvc        