apiVersion: v1
kind: Service

metadata:
  name: mysql-service

spec:
  # type: NodePort
  type: ClusterIP # For Only internal communication in k8s cluster
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      # nodePort: 30002