apiVersion: v1
kind: Service

metadata:
  name: spring-service

spec:
  type: NodePort # Expose the service outside the cluster
  selector:
    app: backend-app # Select the pods with the label app: backend-app
  ports:
    - protocol: TCP
      port: 8080 # Port exposed by the service
      targetPort: 8080 # Port on the pod
      nodePort: 30000 # Port on the node
